# Generated by Django 4.2.13 on 2024-06-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('years_of_experience', models.IntegerField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('salary', models.IntegerField()),
                ('hire_date', models.DateField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
