# Generated by Django 2.2.12 on 2024-07-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_student_id'),
        ('teacher', '0002_auto_20240712_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
