# Generated by Django 4.2.14 on 2024-07-19 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0004_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('class_code', models.CharField(max_length=50)),
                ('room_allocation', models.CharField(max_length=100)),
                ('no_of_tables', models.PositiveSmallIntegerField()),
                ('no_of_students', models.PositiveSmallIntegerField()),
                ('class_representative', models.CharField(max_length=100)),
                ('class_goals', models.TextField()),
                ('class_meeting', models.CharField(max_length=100)),
                ('period_entity', models.CharField(max_length=100)),
                ('student_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
