# Generated by Django 4.2.13 on 2024-06-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('class_code', models.CharField(max_length=50)),
                ('room_allocation', models.CharField(max_length=100)),
                ('no_of_tables', models.PositiveSmallIntegerField()),
                ('no_of_students', models.PositiveSmallIntegerField()),
                ('class_representative', models.CharField(max_length=100)),
                ('class_goals', models.TextField()),
                ('class_meeting', models.CharField(max_length=100)),
                ('period_entity', models.CharField(max_length=100)),
            ],
        ),
    ]
